os:
  - osx
  - windows
language: go
go:
  - 1.13.x
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install 7zip; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export "PATH=/c/Program Files/7-Zip:/c/Users/travis/gopath/bin:$PATH"; fi
install:

script:
  # building MacOS binary
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then go build -o go-backup-mac-x64 && chmod a+x go-backup-mac-x64; fi
  # building Linux binary
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CGO_ENABLED=0; export GOOS=linux; export GOARCH=amd64; go build -o go-backup-linux-x64 && chmod a+x go-backup-linux-x64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CGO_ENABLED=0; export GOOS=linux; export GOARCH=386; go build -o go-backup-linux-x86 && chmod a+x go-backup-linux-x86; fi
  # building Windows binary
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export CGO_ENABLED=0; export GOOS=windows; export GOARCH=amd64; go build -o go-backup-windows-x64.exe; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export CGO_ENABLED=0; export GOOS=windows; export GOARCH=386; go build -o go-backup-indows-x86.exe; fi

before_deploy:
  - export RELEASE_TITLE=$(date '+%Y%m%d%H%M%S')-$TRAVIS_JOB_NUMBER
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 7z a -tzip go-backup-$TRAVIS_TAG-linux-x86.zip go-backup-linux-x86; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 7z a -tzip go-backup-$TRAVIS_TAG-linux-x64.zip go-backup-linux-x64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 7z a -tzip go-backup-$TRAVIS_TAG-mac-x64.zip go-backup-mac-x64; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 7z.exe a -tzip go-backup-$TRAVIS_TAG-win-x86.zip go-backup-windows-x86.exe; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 7z.exe a -tzip go-backup-$TRAVIS_TAG-win-x64.zip go-backup-windows-x64.exe; fi
deploy:
  provider: releases
  name: Release $TRAVIS_TAG ($RELEASE_TITLE)
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: TxzJAhX1cg3vYlEPI5fVeSQK3GcCk7M1OzcotGejAC8wf2dPLqiNGK/aJj7wUoLm8d9oh7lcRjdQpSzaFSzkoSw8YYVHIjKADIt7CcXTQNXRJbjCuj5oJUxssQmrcVEulYzufjwXuqFr5Qy0H30cqb9JG+6gpuM5zUL4m3dew41rmu3tN9EsW24i7fB3rrvzxdO7l5CUZoL2Y4tc5jsROWo+yg8pwlFkisdzlpxL5MkOa5eVYElxvA+PNWxgmxNZkWsfhS+OwNZBvE9P0+ocTg6TNEZLSCV3FvBUVAxYECMECDkiMwuVYYW3dhCXoVORXl27d8pxwC0nsCmso417CUwyGEG7ZkRxgCHQkBY5/gRIULvSTQDJgjpXYJzBrip2ipvUd/7CwFwRz6CkDPye3tAL5vLvRBgRiU/jgXxVyb/28yVf5uTCehWHPrNohwQ0SSBWglbKMojZ45megxH2FzxWeBKbg7+J3Rowjd3tG31EyBef0USpvpOq0RI3MfmOMAL/AredvHPHN9VWRlVi0C2hCLY1k4Pe7MAe6X795wqr65TWgNUlv33DPhQRNNhPWwlhgKnNcGnJ0XdRJDia/m3aJTTrZtnjVP6p3EmthlDlMPr8QQ5cfvXduetq7h4hd+b2Lw4Gh39aPeGCgN95oSwt3I563Gy9ULzlBCi8KD4=
  file:
    - go-backup-$TRAVIS_TAG-win-x86.zip
    - go-backup-$TRAVIS_TAG-win-x64.zip
    - go-backup-$TRAVIS_TAG-linux-x86.zip
    - go-backup-$TRAVIS_TAG-linux-x64.zip
    - go-backup-$TRAVIS_TAG-mac-x64.zip
  draft: true
  on:
    repo: NightMan-1/go-backup
    tags: true
    all_branches: true
